# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: horizon_development
  username: <%= Rails.application.credentials[Rails.env][:db_user] %>
  password:  <%= Rails.application.credentials[Rails.env][:db_password] %>

test:
  <<: *default
  database: horizon_test

production:
  <<: *default
  database: horizon_productiion
  username: <%= Rails.application.credentials[Rails.env][:db_user] %>
  password:  <%= Rails.application.credentials[Rails.env][:db_password] %>
  url: <%= Rails.application.credentials[Rails.env][:db_url] %>
